kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ template "app.fullname" . }}-server
spec:
  issuerRef:
    name: {{ template "app.fullname" . }}-ca-root
    kind: ClusterIssuer
  secretName: {{ template "app.fullname" . }}-server-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - {{ template "app.fullname" . }}-service.{{ template "app.fullname" . }}.svc
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
    - server auth
