kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-cr
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list", "watch", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-crb
subjects:
- kind: ServiceAccount
  name: admission-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: admission-cr
  apiGroup: rbac.authorization.k8s.io
