apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-validation
  annotations:
    cert-manager.io/inject-ca-from: default/client
webhooks:
  - name: pod-validation.default.svc
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: admission-server
        namespace: default
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    sideEffects: None
    timeoutSeconds: 5
