apiVersion: v1
kind: Pod
metadata:
  name: webserver-01
  labels:
    test-label: whatever
spec:
  containers:
    - name: webserver
      image: nginx:latest
      ports:
        - containerPort: 80
