apiVersion: v1
kind: Pod
metadata:
  name: webserver-03
  labels:
    test-label: test-value
spec:
  containers:
    - name: webserver
      image: nginx:latest
      ports:
        - containerPort: 80
